#!/bin/bash
#SBATCH --job-name=CR25
#SBATCH --mem=32G
#SBATCH --nodes=1
#SBATCH --ntasks=27
#SBATCH --cpus-per-task=1
#SBATCH --time=7:0:0    
#SBATCH --mail-user=darasamii@gmail.com
#SBATCH --mail-type=ALL
#SBATCH --account=def-tembelym
#SBATCH --output=submit.out


rm -r processor*
# Step 3: Decompose the domain for parallel processing
decomposePar -copyZero 2>&1  | tee ./logs/log.decomposePar;

# Step 4: Run snappyHexMesh in parallel on 4 cores
mpirun -np 4 snappyHexMesh -dict ./system/snappyHexMeshDictLayer -overwrite -parallel 2>&1  | tee ./logs/log.snappyHexMesh;

# Optional Step 5: Reconstruct the final mesh (combine into single mesh)
#reconstructPar -constant 2>&1  | tee ./logs/log.reconstructPar;
#reconstructParMesh -constant 2>&1  | tee ./logs/log.reconstructPar;


#rm -r processor*

#renumberMesh -overwrite 2>&1 | tee logs/log.renumberMesh;

#Speed steps
#decomposePar 2>&1  | tee ./logs/log.decomposePar2;


#mpirun -np $numProcs foamRun -parallel 2>&1  | tee ./logs/log.foamRun;